version: '3.9'
services:
  client:
    build: client
    ports:
      - '3000:3000'
    volumes:
      - ./client:/usr/app
      - /usr/app/build
      - /usr/app/node_modules
  categories:
    build: categories
    ports:
      - '4001:4001'
    volumes:
      - ./categories:/usr/app
      - /usr/app/node_modules
  event-bus:
    build: event-bus
    volumes:
      - ./event-bus:/usr/app
      - /usr/app/node_modules
  sheets:
    build: sheets
    ports:
      - '4000:4000'
    volumes:
      - ./sheets:/usr/app
      - /usr/app/node_modules
  items:
    build: items
    ports:
      - '4002:4002'
    volumes:
      - ./items:/usr/app
      - /usr/app/node_modules
  query:
    build: query
    ports:
      - '4003:4003'
    volumes:
      - ./query:/usr/app
      - /usr/app/node_modules
  
  sheets-db:
    image: mongo:latest
    volumes:
      - sheets-data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: secret
  
  categories-db:
    image: mongo:latest
    volumes:
      - categories-data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: secret
  
  items-db:
    image: mongo:latest
    volumes:
      - items-data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: secret
  
  query-db:
    image: mongo:latest
    volumes:
      - query-data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: secret

volumes:
  sheets-data:
  categories-data:
  items-data:
  query-data:
